### ISSUE TITLE
background color becomes orange when set to seti colorsheme

### ISSUE THREAD

**Issue by shangsunset** [trusktr/seti.vim#2]
Hi,

I tried installing seti.vim and setting colorscheme to seti but the dark background turned to orange.
![screen shot 2015-04-22 at 11 59 56 am](https://cloud.githubusercontent.com/assets/3700269/7279103/82c16bee-e8e7-11e4-8f39-cd1dca6e96c2.png)

this is my setting:

syntax enable  
set t_Co=256
set background=dark
colorscheme seti

any idea why this is happening? i was using base16 before this. thanks.

**Comment by trusktr** [comment]
@shangsunset Hello!

> set t_Co=256

Are you in terminal vim? I haven't tried it there. I've been using MacVim. Try double checking your terminal color configuration.

**Comment by shangsunset** [comment]
@trusktr  Hey,

Its because i set my shell theme to be base16 previously when i was using base16. its working correctly now. thanks.

**Comment by trusktr** [comment]
Sweeet!

**Comment by nemanjan00** [comment]
I have the same problem. How did you solve this? 

I am using termite with seti-ui theme...
