### ISSUE TITLE
Light blue background on lines without text

### ISSUE THREAD

**Issue by garand** [trusktr/seti.vim#5]
I just installed this and I'm getting a light blue background wherever there isn't text. Any idea why?
<img width="1280" alt="screen shot 2016-03-27 at 10 08 20 am" src="https://cloud.githubusercontent.com/assets/82437/14065764/d4abecd0-f404-11e5-8b1b-79fd67315f66.png">

When there is text, it's fine though.
<img width="1280" alt="screen shot 2016-03-27 at 10 15 59 am" src="https://cloud.githubusercontent.com/assets/82437/14065768/f4845ea2-f404-11e5-8378-770c2da9fad3.png">

**Comment by trusktr** [comment]
Interesting. I myself am not a colorscheme expert. I'd like to find out why too. I believe it's a matter of knowing the name for that highlight group. There's quite a tons of different things that are possible to color that this theme actually doesn't even touch. Let's see if we can find what group that is...

**Comment by trusktr** [comment]
Sorry it's been so long. Looking to merge your PR. I'm not able to reproduce in iTerm. What are you using?

**Comment by ghost** [comment]
I have the same issue plus the background colour is set to black. I am using iterm2 (with terminal type set to xterm-256color) with neovim 0.1.7.

**Comment by teddyhwang** [comment]
Adding the following in `~/.vimrc` helped for me:

```
hi NonText ctermbg=NONE
```
