### ISSUE TITLE
Missing version number

### ISSUE THREAD

**Issue by xyproto** [trusktr/seti.vim#6]
Hi,

seti.vim is available for Arch Linux as the `vim-seti` package. But there is no version number anywhere, so it's hard to tell when a new release has been made and the package should be updated.

Please provide a version number somewhere (in README.md + git tag is a possibility).

Thanks

**Comment by trusktr** [comment]
@xyproto Hello Alexander, there we go! https://github.com/trusktr/seti.vim/commit/a4781817e75a627b54403a92683516aee6230091
Thanks!

**Comment by xyproto** [comment]
Great, thanks

**Comment by xyproto** [comment]
Please also consider adding a git tag, and a license file.

Especially a license file is needed for vim-seti to continue to be an official Arch Linux package.
